definitions:
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
  schema.HTTPError:
    type: object
  schema.LoginReq:
    properties:
      password:
        type: string
      user_name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: login เข้าสู่ระบบเพื่อสร้าง jwt token
      parameters:
      - description: ' request body '
        in: body
        name: request
        schema:
          $ref: '#/definitions/schema.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.HTTPError'
      summary: Login เข้าสู่ระบบ
      tags:
      - AUTH
  /api/users/getuser:
    get:
      consumes:
      - application/json
      description: Show User ตามเงื่อนไข
      parameters:
      - in: query
        name: created_at
        type: string
      - in: query
        name: email
        type: string
      - in: query
        name: id
        type: integer
      - in: query
        name: updated_at
        type: string
      - in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: ค้นหา User ตามเงื่อนไข
      tags:
      - User
  /api/users/users2:
    get:
      consumes:
      - application/json
      description: แสดงข้อมูลทั้งหมดแบบไม่มีเงื่อนไข
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: แสดงข้อมูล User ทั้งหมด
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: ใส่ค่า Bearer เว้นวรรคและตามด้วย TOKEN  ex(Bearer ?????????)
    name: Authorization
    type: apiKey
swagger: "2.0"
